export const PLAYER_NAME_FORM_INPUT = 'playerName',
CHAT_MESSAGE_FORM_INPUT_NAME = 'chatMessage',
MAP_TILE_SIZE = 16,
SPRITESHEET_ROWS = 23,
SPRITESHEET_COLUMNS = 14,
BACKGROUND_TILE_Z_INDEX = 2,
PLAYER_TILE_Z_INDEX = 0