import { GRASS, SOLID } from "./consts.js";

export const baseMap = [
  // 11 rows, 17 columns
  [SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID],
];


export const blockMap = [
  
]