import { GRASS, SOLID } from "./consts.js";

export const baseMap = [
  // 11 rows, 17 columns
  [SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID, GRASS, SOLID],
  [SOLID, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SOLID],
  [SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID, SOLID],
];

/*
SPAWN - normal GRASS, not allowed to spawn SOLID or DBLOCK on it
SOLID - blocks you can not destroy, like game edge
DBLOCK - normal destroyable block
DBLOCKBOMB - destroyable block with a bomb powerup spawned when destroyed
DBLOCKFLAME - destroyable block with flame powerup spawned when destroyed
DBLOCKSPEED - destroyable block with player speed increase powerup spawned when destroyed
*/